apiVersion: v1
kind: PersistentVolume
metadata: 
  name: bdmonedas-pv
  namespace: bdmonedas
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres"
  persistentVolumeReclaimPolicy: Delete

  