apiVersion: v1
kind: PersistentVolume
metadata: 
  name: bdmonedas-pv
spec:
  capacity:
    storage: 16i
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres"
  persistentVolumeClaimPolicy: Delete

  
