apiVersion: v1
kind: Service
metadata: 
  name: bdmonedas-servicio
  namespace: bdmonedas
spec:
  selector:
    app: bdmonedas
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  
