apiVersion: batch/v1
kind: Job
metadata:
  name: iniciar-bdmonedas
  namespace: bdmonedas
spec:
  template:
    spec:
      containers:
        - name: iniciar-bdmonedas
          image: postgres:16
          command: ["sh", "-c", "echo 'Iniciando base de datos bdmonedas...' && sleep 10"]
          env:
            - name: POSTGRES_DB
              value: "monedas"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bdmonedas-secretos
                  key: db-password
      restartPolicy: OnFailure
  backoffLimit: 4
  completions: 1
  parallelism: 1
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 600