apiVersion: batch/v1
kind: Job
metadata:
  name: iniciar-bdmonedas
spec:
  restartPolicy: Never
  containers: 
  - name: iniciar-bdmonedas
    imagen: postgres:16
    command: ["/bin/bash", "-c"]
    args:
    - |